[package]
name = "initialize"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "6.0.0"
inquire = "0.9.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
strum = "0.27.2"
strum_macros = "0.27.2"
thiserror = "2.0.18"
